# Data exploration with Pandas

## Setup Notebook and Kernel
The file is placed in the folder `day_72/` and the kernel used is the uv .venv inside the root folder `100-DAYS-OF-PYTHON/`
<div style="background:Gainsboro; border-left:4px solid DodgerBlue; padding:10px; padding-left:10 px; width:800px; border-radius:6px;">
<strong style="color:DodgerBlue;">ⓘ Note</strong>
<p style="margin-bottom:5px;">
The choice to go with a local kernel is because Google Colab forces steps to work from its platform.<br>  
Pandas works mainly with CPU so for now no need to use GPUs and the code can be committed.
</p>
</div>

In [ ]:
import pandas as pd

df = pd.read_csv("salaries_by_college_major.csv")
df.head() # Show the top 5 rows of the dataframe

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

## Exploring data

### Shape of the table and column names

In [10]:
df.shape, df.columns

((51, 6),
 Index(['Undergraduate Major', 'Starting Median Salary',
        'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
        'Mid-Career 90th Percentile Salary', 'Group'],
       dtype='str'))

### NaN (Not A Number) check
Use the `isna()` combined with `any()` that works with boolean data with `axis=1` that goes in row-wise direction (`axis=0` goes column-wise).

In [12]:
df.isna().tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [13]:
df.isna().any()

Undergraduate Major                  False
Starting Median Salary                True
Mid-Career Median Salary              True
Mid-Career 10th Percentile Salary     True
Mid-Career 90th Percentile Salary     True
Group                                 True
dtype: bool

Create a mask with `.any()` and `axis=1`. While `df.isna().any(axis=1)` gives back a **Series of booleans** with the same length as the dataframe, it means it can be used as a mask for the dataframe.  
It means we can have a table where only the row that has at least (any) columns with value NaN will appear.

In [18]:
df[df.isna().any(axis=1) == True]

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

## Edit rows
Use `dropna()` to drop the last row that simply refers to the source and it is not usable.

In [ ]:
clean_df = df.dropna()
# Check the tail to confirm the row was dropped
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS